/**
    Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

    Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at

        http://aws.amazon.com/apache2.0/

    or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

module.exports = {
	"geek lab": "Welcome to the sayli's lab. I am here to tell you about the present inventory in the lab. I am also here to help you find the right component to make the project. For Example - just say tripple five circuit or just say - what are some good projects in our lab.",
	"projects": "Yes, There are many projects in our lab. But my personal favorites are a 4 bit adder circuit made with discrete components and a telepresence table top robot. If you want to see the projects, ask me to  trigger awesome projects.",
	"development board": "Yes, We have development boards from basic to advance level microcontrollers. Some of them are : eight zero five one microcontroller board, pic, raspberry pi b plus, chronos development board for smart watch etc. If you want to start working on the development board then ask me to trigger d board. I will show the location of the board in the lab.",
	"development boards": "Yes, We have development boards from basic to advance level microcontrollers. Some of them are : eight zero five one microcontroller board, pic, raspberry pi b plus, chronos development board for smart watch etc. If you want to start working on the development board then ask me to trigger d board. I will show the location of the board in the lab.",
	"hands on": "We have a lot of components to make exciting projects. But there is currently two projects you might want to make for you. The first one is mobile robot that consist of a robot chasis, geared dc motor, wheeels, tyer and the second one is the kit of lego mindstrom n x t. If you want to make any of these, ask me to  trigger make project and I will show you the location of the projects kit, tools , and surplus components.",
	"sensors": "We have lots of different types of sensors. Some of the exciting sensors are : alchohol sensor, dust sensor, air quality sensor, gas sensor, hear rate sensor. We also have a special sensor and device which can detect the overing of the hand and other sensor device is a coin acceptor in which you can train upto 6 types of different coins. If you would like to start developing with the sensors then ask me to trigger sensor. I will show the location of the sensor box in our lab.",
	"sensors": "We have lots of different types of sensors. Some of the exciting sensors are : alchohol sensor, dust sensor, air quality sensor, gas sensor, hear rate sensor. We also have a special sensor and device which can detect the overing of the hand and other sensor device is a coin acceptor in which you can train upto 6 types of different coins. If you would like to start developing with the sensors then ask me to trigger sensor. I will show the location of the sensor box in our lab.",
	"books": "We have magazines and books in the lab. I can help you find a good book. I suggest five five five timer circuit is good one to begin. Ask me to  trigger books and I will show you the location of books in the lab. And please don't forget to keep the book in the same place after your reading is over.",
	"geeks lab": "Welcome to the sayli's lab. I am here to tell you about the present inventory in the lab. I am also here to help you find the right component to make the project. ask me to  trigger tripple five circuit",
	"tripple five circuit": "Monostable Multivibrator is also known as One Short Multivibrator. As its name indicates it has one stable state and it switches to unstable state for a predetermined time period T when it is triggered. The time period T is determined by the RC time constant in the circuit. Monostable mode of 555 Timer is commonly used for generating Pulse Width Modulated (PWM) waves.	You will need the following components : 1 k resistor, 10 k resistor, 2 0 point 1 micro farad capacitor, 555 timer IC, 5 volt power supply, breadboard, single core wires, led and 270k resistor. If you want to build the circuit, please trigger the word tripple five make.",
    "timer circuit": "Monostable Multivibrator is also known as One Short Multivibrator. As its name indicates it has one stable state and it switches to unstable state for a predetermined time period T when it is triggered. The time period T is determined by the RC time constant in the circuit. Monostable mode of 555 Timer is commonly used for generating Pulse Width Modulated (PWM) waves.	You will need the following components : 1 k resistor, 10 k resistor, 2 0 point 1 micro farad capacitor, 555 timer IC, 5 volt power supply, breadboard, single core wires, led and 270k resistor. If you want to build the circuit, please trigger the word tripple five make."
};
